export const LOGIN = "LOGIN";

export const ROOT = "NOCALHOST";

export const APP = "APP";
export const APP_FOLDER = "APP_FOLDER";

export const NETWORK_FOLDER = "NETWORK_FOLDER";
export const SERVICE_FOLDER = "SERVICE_FOLDER";
export const SERVICE = "SERVICE";

export const CONFIGURATION_FOLDER = "CONFIGURATION_FOLDER";
export const CONFIG_MAP_FOLDER = "CONFIG_MAP_FOLDER";
export const CONFIG_MAP = "CONFIG_MAP";
export const SECRET_FOLDER = "SECRET_FOLDER";
export const SECRET = "SECRET";
export const HPA_FOLDER = "HPA_FOLDER";
export const HPA = "HPA";
export const RESOURCE_QUOTA_FOLDER = "RESOURCE_QUOTA_FOLDER";
export const RESOURCE_QUOTA = "RESOURCE_QUOTA";
export const POD_DISRUPTION_BUDGET_FOLDER = "POD_DISRUPTION_BUDGET_FOLDER";
export const POD_DISRUPTION_BUDGET = "POD_DISRUPTION_BUDGET";

export const WORKLOAD_FOLDER = "WORKLOAD_FOLDER";
export const DEPLOYMENT_FOLDER = "DEPLOYMENT_FOLDER";
export const DEPLOYMENT = "DEPLOYMENT";
export const STATEFUL_SET_FOLDER = "STATEFUL_SET_FOLDER";
export const STATEFUL_SET = "STATEFUL_SET";
export const DAEMON_SET_FOLDER = "DAEMON_SET_FOLDER";
export const DAEMON_SET = "DAEMON_SET";
export const JOBS_FOLDER = "JOBS_FOLDER";
export const JOB = "JOB";
export const CRON_JOBS_FOLDER = "CRON_JOBS_FOLDER";
export const CRON_JOB = "CRON_JOB";
export const PODS_FOLDER = "PODS_FOLDER";
export const POD = "POD";

export const KUBERNETE_RESOURCE = "KUBERNETE_RESOURCE";
export const KUBERNETE_FOLDER_RESOURCE = "KUBERNETE_FOLDER_RESOURCE";

export const ID_SPLIT = "-*.";
