export const LOGIN = "LOGIN";

export const ROOT = "NOCALHOST";

export const APP = "APP";
export const APP_FOLDER = "APP_FOLDER";

export const NETWORK_FOLDER = "NETWORK_FOLDER";
export const SERVICE_FOLDER = "SERVICE_FOLDER";
export const SERVICE = "SERVICE";
export const ENDPOINT_FOLDER = "ENDPOINT_FOLDER";
export const ENDPOINT = "ENDPOINT";
export const INGRESS_FOLDER = "INGRESS_FOLDER";
export const INGRESS = "INGRESS";
export const NETWORK_POLICIES_FOLDER = "NETWORK_POLICIES_FOLDER";
export const NETWORK_POLICIES = "NETWORK_POLICIES";

export const CONFIGURATION_FOLDER = "CONFIGURATION_FOLDER";
export const CONFIG_MAP_FOLDER = "CONFIG_MAP_FOLDER";
export const CONFIG_MAP = "CONFIG_MAP";
export const SECRET_FOLDER = "SECRET_FOLDER";
export const SECRET = "SECRET";
export const HPA_FOLDER = "HPA_FOLDER";
export const HPA = "HPA";
export const RESOURCE_QUOTA_FOLDER = "RESOURCE_QUOTA_FOLDER";
export const RESOURCE_QUOTA = "RESOURCE_QUOTA";
export const POD_DISRUPTION_BUDGET_FOLDER = "POD_DISRUPTION_BUDGET_FOLDER";
export const POD_DISRUPTION_BUDGET = "POD_DISRUPTION_BUDGET";

export const STORAGE_FOLDER = "STORAGE_FOLDER";
export const PERSISTENT_VOLUME_FOLDER = "PERSISTENT_VOLUME_FOLDER";
export const PERSISTENT_VOLUME = "PERSISTENT_VOLUME";
export const PERSISTENT_VOLUME_CLAIM_FOLDER = "PERSISTENT_VOLUME_CLAIM_FOLDER";
export const PERSISTENT_VOLUME_CLAIM = "PERSISTENT_VOLUME_CLAIM";
export const STORAGE_CLASS_FOLDER = "STORAGE_CLASS_FOLDER";
export const STORAGE_CLASS = "STORAGE_CLASS";

export const WORKLOAD_FOLDER = "WORKLOAD_FOLDER";
export const DEPLOYMENT_FOLDER = "DEPLOYMENT_FOLDER";
export const DEPLOYMENT = "DEPLOYMENT";
export const STATEFUL_SET_FOLDER = "STATEFUL_SET_FOLDER";
export const STATEFUL_SET = "STATEFUL_SET";
export const DAEMON_SET_FOLDER = "DAEMON_SET_FOLDER";
export const DAEMON_SET = "DAEMON_SET";
export const JOBS_FOLDER = "JOBS_FOLDER";
export const JOB = "JOB";
export const CRON_JOBS_FOLDER = "CRON_JOBS_FOLDER";
export const CRON_JOB = "CRON_JOB";
export const PODS_FOLDER = "PODS_FOLDER";
export const POD = "POD";
export const CRD_FOLDER = "CRD_FOLDER";
export const CRD = "CRD";

export const KUBERNETE_RESOURCE = "KUBERNETE_RESOURCE";
export const KUBERNETE_FOLDER_RESOURCE = "KUBERNETE_FOLDER_RESOURCE";

export const ID_SPLIT = "-*.";
