name: Unit Tests
on:
  push:
    branches: [ webview_integration ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ^14

      - uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-ui-test-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-ui-test

      - uses: pnpm/action-setup@v2.1.0
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        with:
          version: 6
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Run tests
        run: npm run test