name: UI Tests
on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [test/vscode-puppeteer]
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest]
        # [ubuntu-latest]
        # [windows-latest]
        # [windows-latest,ubuntu-latest]
        # [windows-latest,ubuntu-latest,macos-latest]

    name: Run UI Tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Create cluster
        env:
          TKE_SECRET_ID: ${{ secrets.TKE_SECRET_ID }}
          TKE_SECRET_KEY: ${{ secrets.TKE_SECRET_KEY }}
        run: |
          curl -fL "https://nocalhost-generic.pkg.coding.net/nocalhost-test/binary/tketools?version=latest" -o ~/cluster
          chmod +x ~/cluster
          ~/cluster create &> ~/cluster.log &

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ^14

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install project dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      # - name: Run tests
      #   uses: GabrielBB/xvfb-action@v1.0
      #   env:
      #     KUBECONFIG_PATH: ~/config
      #   with:
      # run: yarn run test:ext

      - name: Set plugin version
        run: echo "PLUGIN_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update the version of package.json
        env:
          MINIMUNM_VERSION_REQUIREMENT: ${{ secrets.MINIMUNM_VERSION_REQUIREMENT }}
          NHCTL_VERSION: dev
        run: node scripts/gitVersion.js

      - name: Build ext
        run: |
          yarn run build:ext
          rm -rf .vscode-test
          ls -al

      - name: Wait cluster ready
        run: >-
          while [ ! -f "${HOME}/config" ];do
            tail -n 5 ~/cluster.log
            sleep 10s;
          done

      - name: Set kubeconfig
        run: |
          NOCALHOST_KUBECONFIG=$(cat ~/config)
          echo "NOCALHOST_KUBECONFIG<<EOF" >> $GITHUB_ENV
          echo "$NOCALHOST_KUBECONFIG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "::add-mask::$NOCALHOST_KUBECONFIG"

      - name: Run tests
        env:
          CYPRESS_EVERY_NTH_FRAME: 1
          # LOGGER_LEVEL: DEBUG
        run: yarn run test:ext

      # - name: Destroy cluster
      #   if: ${{ always() }} failure
      #   env:
      #     TKE_SECRET_ID: ${{ secrets.TKE_SECRET_ID }}
      #     TKE_SECRET_KEY: ${{ secrets.TKE_SECRET_KEY }}
      #   run: ~/cluster destroy

      - name: Artifact screenshot
        if: ${{ always() }}
        run: mv .screenshot ~/.nh/screenshot

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: artifact-${{ runner.os }}-${{ github.run_id }}
          path: |
            ~/.nh/screenshot
            ~/.nh/nhctl/logs/nhctl.log
            ~/.nh/vscode-plugin/vsc_log

      - name: Artifact dependency
        if: ${{ failure() }}
        run: |
          mkdir .dependency
          cp ~/.nh/bin/nhctl .dependency/
          cp nocalhost.vsix .dependency/
          cp ~/config .dependency/

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: artifact-${{ runner.os }}-${{ github.run_id }}-dependency
          path: .dependency
