name: UI Tests
on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [test/ubuntu-test]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Run UI Tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: ^14

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6
          run_install: false

      - uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-ui-test-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-ui-test

      - uses: pnpm/action-setup@v2.1.0
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        with:
          version: 6
          run_install: |
            - args: [--frozen-lockfile]

      - name: Build ext
        env:
          MINIMUNM_VERSION_REQUIREMENT: ${{ secrets.MINIMUNM_VERSION_REQUIREMENT }}
          NHCTL_VERSION: dev
        run: |
          pnpm run build:test
          rm -rf .vscode-test

      - name: Start xvfb
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sudo apt-get update -y
          sudo apt-get install -y xclip

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Run tests
        timeout-minutes: 20
        env:
          CYPRESS_EVERY_NTH_FRAME: 1
          VIDEO_CAPTURE: 1
          LOGGER_LEVEL: ALL
          DISPLAY: :99.0
        run: pnpm run test:ext

      - name: Artifact screenshot
        if: ${{ failure() }}
        run: |
          mkdir -p ~/.nh/screenshot
          mv .screenshot/* ~/.nh/screenshot

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: artifact-${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}
          path: |
            ~/.nh/screenshot
            ~/.nh/nhctl/ns
            ~/.nh/nhctl/logs/nhctl.log
            ~/.nh/vscode-plugin/vsc_log