name: UI Tests
on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [test/vcluster]
jobs:
  test:
    strategy:
      matrix:
        os: [macos-10.15]
        # [ubuntu-latest]
        # [windows-latest]
        # [windows-latest,ubuntu-latest]
        # [windows-latest,ubuntu-latest,macos-latest]
    name: Run UI Tests
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ^14

      - uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-ui-test-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-build

      - uses: pnpm/action-setup@v2.1.0
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        with:
          version: 6
          run_install: |
            - args: [--frozen-lockfile]

      # - name: Run tests
      #   uses: GabrielBB/xvfb-action@v1.0
      #   env:
      #     KUBECONFIG_PATH: ~/config
      #   with:
      # run: yarn run test:ext

      - name: Build ext
        env:
          MINIMUNM_VERSION_REQUIREMENT: ${{ secrets.MINIMUNM_VERSION_REQUIREMENT }}
          NHCTL_VERSION: dev
        run: |
          yarn run build:ext
          rm -rf .vscode-test
          ls -al

      - name: Create cluster
        id:  create-cluster
        uses: zhangjian10/nocalhost-server-cli@v0.0.8
        with:
          host: ${{ secrets.NOCALHOST_VCLUSTER_HOST_FOR_TEST }}
          email: ${{ secrets.NOCALHOST_VCLUSTER_EMAIL_FOR_TEST }}
          password: ${{ secrets.NOCALHOST_VCLUSTER_PASSWORD_FOR_TEST }}
          action: devSpace.create

      - name: Run tests
        timeout-minutes: 20
        env:
          CYPRESS_EVERY_NTH_FRAME: 1
          VIDEO_CAPTURE: 1
        run: yarn run test:ext

      - name: Destroy cluster
        if: ${{ always() }}
        uses: zhangjian10/nocalhost-server-cli@v0.0.8
        with:
          host: ${{ secrets.NOCALHOST_VCLUSTER_HOST_FOR_TEST }}
          email: ${{ secrets.NOCALHOST_VCLUSTER_EMAIL_FOR_TEST }}
          password: ${{ secrets.NOCALHOST_VCLUSTER_PASSWORD_FOR_TEST }}
          action: devSpace.remove
          parameters: ${{ steps.create-cluster.outputs.space_id }}

      - name: Artifact screenshot
        if: ${{ always() }}
        run: |
          mkdir -p ~/.nh/screenshot
          mv .screenshot/*.jpeg ~/.nh/screenshot
          cp ~/.kube/config  ~/.nh

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: artifact-${{ runner.os }}-${{ github.run_id }}
          path: |
            ~/.nh/screenshot
            ~/.nh/nhctl/ns
            ~/.nh/nhctl/logs/nhctl.log
            ~/.nh/vscode-plugin/vsc_log

      - name: Artifact dependency
        if: ${{ failure() }}
        run: |
          mkdir .dependency
          mv .screenshot/*.mp4 .dependency/
          cp ~/.nh/bin/nhctl .dependency/
          cp nocalhost.vsix .dependency/

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: artifact-${{ runner.os }}-${{ github.run_id }}-dependency
          path: .dependency
