name: UI Tests
on:
  push:
    branches: [ test/vscode-puppeteer ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest]
        # [ubuntu-latest]
        # [windows-latest]
        # [windows-latest,ubuntu-latest]
        # [windows-latest,ubuntu-latest,macos-latest]
        
    name: Run UI Tests
    runs-on: ${{ matrix.os }}
    steps:

      - name: Create cluster
        env:
          TKE_SECRET_ID: ${{ secrets.TKE_SECRET_ID }}
          TKE_SECRET_KEY: ${{ secrets.TKE_SECRET_KEY }}
        run: |
          curl -fL "https://codingcorp-generic.pkg.coding.net/nocalhsot-test/cluster/cluster?version=latest" -o ~/cluster
          chmod +x ~/cluster
          ~/cluster create
          
      - name: Set Env
        run: echo "NOCALHOST_KUBECONFIG=$(cat ~/.kube/config)" >> $GITHUB_ENV
      
      - name: Destroy cluster
        if: ${{ always() }}
        env:
          TKE_SECRET_ID: ${{ secrets.TKE_SECRET_ID }}
          TKE_SECRET_KEY: ${{ secrets.TKE_SECRET_KEY }}
        run: ~/cluster destroy
        
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: ^14

      - uses: GabrielBB/xvfb-action@v1.0

      - uses: actions/cache@v2
        id: yarn-cache 
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install project dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' 
        run: yarn    

      - name: Build ext
        run: yarn run build:ext

      - name: Run tests
        run: yarn run test:ext

      - name: Mv screenshot
        if: ${{ always() }}
        run: |
          mv .screenshot ~/.nh/screenshot
          
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: artifact-${{ runner.os }}-${{ github.run_id }}
          path: |
            ~/.nh/screenshot
            ~/.nh/nhctl/logs/nhctl.log
            ~/.nh/vscode-plugin/vsc_log
