name: Vscode Test
on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [test/ubuntu-test]
jobs:
  prebuild:
    name: Pre Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6
          run_install: false

      - name: Fetch dependencies from cache
        id: cache-pnpm
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            cache-pnpm-

      - uses: pnpm/action-setup@v2.1.0
        if: steps.cache-pnpm.outputs.cache-hit != 'true'
        with:
          version: 6
          run_install: |
            - args: [--frozen-lockfile]

      - name: Build ext
        env:
          MINIMUNM_VERSION_REQUIREMENT: ${{ secrets.MINIMUNM_VERSION_REQUIREMENT }}
          NHCTL_VERSION: dev
        run: |
          pnpm run build:test

      - name: Upload vsix
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.run_id }}-nocalhost.vsix
          path: nocalhost.vsix

  install:
    needs: prebuild
    name: Test Install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6
          run_install: false

      - name: Fetch dependencies from cache
        id: cache-pnpm
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            cache-pnpm-

      - uses: pnpm/action-setup@v2.1.0
        if: steps.cache-pnpm.outputs.cache-hit != 'true'
        with:
          version: 6
          run_install: |
            - args: [--frozen-lockfile]

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.run_id }}-nocalhost.vsix

      - name: Start xvfb
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Run tests
        timeout-minutes: 20
        env:
          CYPRESS_EVERY_NTH_FRAME: 1
          VIDEO_CAPTURE: 1
          LOGGER_LEVEL: ALL
          DISPLAY: :99.0
        run: pnpm run test-install

      - name: Artifact screenshot
        if: ${{ failure() }}
        run: |
          mkdir -p ~/.nh/screenshot
          mv .screenshot/* ~/.nh/screenshot

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: index
          path: |
            ~/.nh/screenshot
            ~/.nh/nhctl/ns
            ~/.nh/nhctl/logs/nhctl.log
            ~/.nh/vscode-plugin/vsc_log
            
  others:
    needs: prebuild
    name: Test Others
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6
          run_install: false

      - name: Fetch dependencies from cache
        id: cache-pnpm
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            cache-pnpm-

      - uses: pnpm/action-setup@v2.1.0
        if: steps.cache-pnpm.outputs.cache-hit != 'true'
        with:
          version: 6
          run_install: |
            - args: [--frozen-lockfile]

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.run_id }}-nocalhost.vsix

      - name: Start xvfb
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sudo apt-get update -y
          sudo apt-get install -y xclip

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Run tests
        timeout-minutes: 20
        env:
          CYPRESS_EVERY_NTH_FRAME: 1
          VIDEO_CAPTURE: 1
          LOGGER_LEVEL: ALL
          DISPLAY: :99.0
        run: pnpm run test-index

      - name: Artifact screenshot
        if: ${{ failure() }}
        run: |
          mkdir -p ~/.nh/screenshot
          mv .screenshot/* ~/.nh/screenshot

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: index
          path: |
            ~/.nh/screenshot
            ~/.nh/nhctl/ns
            ~/.nh/nhctl/logs/nhctl.log
            ~/.nh/vscode-plugin/vsc_log